### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpsi.jl#6]
test compatibility with ACEschrodinger

**Comment by cortner** [comment]
@CheukHinHoJerry  - I believe you have done this? We can close?

**Comment by CheukHinHoJerry** [comment]
@cortner I think it is better to check again after merging since we changed the eval output, I will try to write a testing code tonight.

**Comment by CheukHinHoJerry** [comment]
@cortner I think this issue can now be closed.

**Comment by cortner** [comment]
Thank you
